"""feat: Next migration

Revision ID: 7641e7407c48
Revises: a85d0e81417c
Create Date: 2024-08-01 17:27:50.054526

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7641e7407c48"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("userId"),
    )

    op.create_table(
        "game",
        sa.Column("gameId", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timeCompression", sa.Float(), nullable=True),
        sa.Column("lastActionTime", sa.DateTime(), nullable=True),
        sa.Column("eventCounter", sa.Integer(), nullable=True),
        sa.Column("startTime", sa.DateTime(), nullable=False),
        sa.Column("endTime", sa.DateTime(), nullable=False),
        sa.Column("deathProbeCost", sa.Integer(), nullable=True),
        sa.Column("spyProbeCost", sa.Integer(), nullable=True),
        sa.Column("factoryCost", sa.Integer(), nullable=True),
        sa.Column("speedCost", sa.Integer(), nullable=True),
        sa.Column("battlePowerCost", sa.Integer(), nullable=True),
        sa.Column("rangeCost", sa.Integer(), nullable=True),
        sa.Column("probeShieldCost", sa.Integer(), nullable=True),
        sa.Column("deathShieldCost", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("gameId"),
    )
    op.create_table(
        "player",
        sa.Column("playerId", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gameId", sa.Integer(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("wealth", sa.Integer(), nullable=True),
        sa.Column("battlePower", sa.Integer(), nullable=True),
        sa.Column("range", sa.Float(), nullable=True),
        sa.Column("speed", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gameId"],
            ["game.gameId"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["user.userId"],
        ),
        sa.PrimaryKeyConstraint("playerId"),
    )
    op.create_table(
        "star",
        sa.Column("starId", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gameId", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("wealth", sa.Integer(), nullable=True),
        sa.Column("numShips", sa.Integer(), nullable=True),
        sa.Column("numFactories", sa.Integer(), nullable=True),
        sa.Column("hasSpyShield", sa.Boolean(), nullable=True),
        sa.Column("hasDeathShield", sa.Boolean(), nullable=True),
        sa.Column("ownerId", sa.Integer(), nullable=True),
        sa.Column("homeWorldOfId", sa.Integer(), nullable=True),
        sa.Column("isDead", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gameId"],
            ["game.gameId"],
        ),
        sa.ForeignKeyConstraint(
            ["homeWorldOfId"],
            ["player.playerId"],
        ),
        sa.ForeignKeyConstraint(
            ["ownerId"],
            ["player.playerId"],
        ),
        sa.PrimaryKeyConstraint("starId"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("star")
    op.drop_table("player")
    op.drop_table("game")
    op.drop_table("user")
    # ### end Alembic commands ###
